### ISSUE TITLE
How to deploy the server?

### ISSUE THREAD

**Issue by it19862** [P4UL-M/Online---chat#1]
I want to test the server.
I'm using Windows-10.
I downloaded the files.
What do I need to install additionally on Windows-10 to test the server?
Where to place the project files?
Where to place and how to run the server file?
Where to place and how to run the client file?

**Comment by P4UL-M** [comment]
Hello,

This server functions with php and mysql so you will need to use web development tools like WAMP or MAMP (I personally used MAMP).

Once you do that, you will need to configure mysql to add the database : ``historique`` (you can put a new name and change the name in the php files. You also need to add a table which looks like that :

``` CREATE TABLE `messages` (
  `id` int(11) NOT NULL,
  `user` varchar(255) NOT NULL,
  `txt` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;```

Id need to be the primary key and in AUTO INCREMENT mode.

Also, to not leak the password and username of my database, I used an .env file. You can either recreate it or directly add your user name and password in the src/chat.php file.

The next thing you need to do is to execute the server with ``php bin/chat-server.php``.

You will also need to rewrite all url redirection in the .js file and the .html file to ``localhost`` and not ``deway.fr``. For the websocket you will need to remove  ``/wss/`` from the link that i used for redirection of the port and pass the protocol to ``ws://`` because you will be on localhost. Also, you need to add the port directly, so basically, your link will look like : ``ws://localhost:8080?pseudo=${pseudo}``. Make sure to open your web server on another port than 8080.

Then you are done and your website is accessible at localhost on the port you configure with MAMP/WAMP.

That seems all to me. I hope I have forgotten nothing. In the other case, feel free to ask.

If you have never used PHP and mysql I advise you on this course on openclassroom. This is the one i used to learn to make this website.
- https://openclassrooms.com/fr/courses/918836-concevez-votre-site-web-avec-php-et-mysql

**Comment by it19862** [comment]
@P4UL-M Thank you so much...
you helped me a lot...

If you have the opportunity, could you please post in the Readme a few pictures of how your application works.

**Comment by P4UL-M** [comment]
Sure thing, also you can check a live exemple [here](https://deway.fr/chat/)

Here is a basic flowchart of the application :
![Chat Online](https://user-images.githubusercontent.com/54858036/170882951-a054fe28-35c2-44fb-9f98-5f103470483d.jpeg)

Basically there is 3 php file that make the application : 
- ``Chat.php`` the main page which redirect to ``index.php`` if there is no pseudo in the cookies. 
- ``index.php``which save the choosen pseudo in the cookies.
- ``change_pseudo.php`` that delete the pseudo from the cookies and redirect to index.php. 

The pseudo is send in args of the GET request to the websocket connection so the server can keep track of every connected users and send them to other users. For the update of the messages, it works with 3 requests: first the server sends to all users that they need to update (in case the server receive a message), then all users send their current last messages and the server send them back the missing message. This way we can be sure that the user will always have all messages in one exemplary.
